
import React from 'react';

interface SummaryViewProps {
  summary: string;
  title: string;
}

const SummaryView: React.FC<SummaryViewProps> = ({ summary, title }) => {
  // Enhanced formatter to handle bold text and better list styling
  const formatText = (text: string) => {
    // Basic regex to handle **bold** text
    const parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="font-bold text-indigo-900">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
  };

  const formatSummary = (text: string) => {
    return text.split('\n').map((line, i) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('# ')) {
        return <h1 key={i} className="text-3xl font-extrabold mt-8 mb-6 text-slate-900 border-b pb-2">{formatText(trimmed.replace('# ', ''))}</h1>;
      }
      if (trimmed.startsWith('## ')) {
        return <h2 key={i} className="text-2xl font-bold mt-8 mb-4 text-indigo-800 flex items-center gap-2">
          <span className="w-1.5 h-6 bg-indigo-500 rounded-full inline-block"></span>
          {formatText(trimmed.replace('## ', ''))}
        </h2>;
      }
      if (trimmed.startsWith('### ')) {
        return <h3 key={i} className="text-xl font-bold mt-6 mb-3 text-slate-800 uppercase tracking-tight">{formatText(trimmed.replace('### ', ''))}</h3>;
      }
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        return (
          <li key={i} className="ml-6 list-none mb-3 text-slate-700 relative pl-6 before:content-['•'] before:absolute before:left-0 before:text-indigo-500 before:font-bold before:text-xl before:-top-1 leading-relaxed">
            {formatText(trimmed.substring(2))}
          </li>
        );
      }
      if (trimmed === '') return <div key={i} className="h-4" />;
      
      return <p key={i} className="mb-4 leading-relaxed text-slate-700 text-lg">{formatText(line)}</p>;
    });
  };

  return (
    <div className="bg-white rounded-3xl shadow-xl border border-indigo-50 p-6 md:p-12 max-w-4xl mx-auto my-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-10 gap-4 border-b border-slate-100 pb-8">
        <div>
          <span className="text-indigo-600 font-bold text-xs uppercase tracking-widest mb-2 block">Comprehensive Summary</span>
          <h1 className="text-3xl md:text-4xl font-black text-slate-900 leading-tight">{title}</h1>
        </div>
        <button 
          onClick={() => window.print()} 
          className="bg-indigo-50 text-indigo-700 px-6 py-3 rounded-2xl hover:bg-indigo-100 font-bold transition-all flex items-center justify-center gap-2 shrink-0 h-fit"
        >
          <i className="fas fa-print"></i> Export PDF
        </button>
      </div>
      <div className="prose prose-indigo max-w-none">
        {formatSummary(summary)}
      </div>
      
      <div className="mt-12 pt-8 border-t border-slate-100 flex items-center justify-between text-slate-400 text-sm italic">
        <p>Generated by studyeasierAI</p>
        <p>{new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
};

export default SummaryView;
